### ISSUE TITLE
Honestly, it's kinda bad!

### ISSUE THREAD

**Issue by Daniel-Boll** [taylorbyks/ignite-template-reactjs-criando-um-hook-de-carrinho-de-compras#1]
# Honestly, it's kinda bad
### Honestly, it's kinda bad
Honestly, it's kinda bad
`Honestly, it's kinda bad`

**Comment by taylorbyks** [comment]
Why? 😥

**Comment by Daniel-Boll** [comment]
Well, I mean, it's honestly kinda bad.
